{
  "openapi": "3.0.1",
  "info": {
    "title": "OpenAPI definition",
    "version": "v0"
  },
  "servers": [
    {
      "url": "http://127.0.0.1:8080",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/api/v1/customers/{documentType}/{document}": {
      "get": {
        "tags": [
          "customer-controller"
        ],
        "operationId": "findByDocument",
        "parameters": [
          {
            "name": "documentType",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "enum": [
                "CC",
                "NIT",
                "FE",
                "PA"
              ]
            }
          },
          {
            "name": "document",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/CustomerResponse"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "customer-controller"
        ],
        "operationId": "update",
        "parameters": [
          {
            "name": "documentType",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "enum": [
                "CC",
                "NIT",
                "FE",
                "PA"
              ]
            }
          },
          {
            "name": "document",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateCustomerRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/CustomerResponse"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "customer-controller"
        ],
        "operationId": "delete_1",
        "parameters": [
          {
            "name": "documentType",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "enum": [
                "CC",
                "NIT",
                "FE",
                "PA"
              ]
            }
          },
          {
            "name": "document",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/products": {
      "get": {
        "tags": [
          "product-controller"
        ],
        "operationId": "findAll",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ProductResponse"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "product-controller"
        ],
        "operationId": "create",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "oneOf": [
                  {
                    "$ref": "#/components/schemas/AddCheckingProductRequest"
                  },
                  {
                    "$ref": "#/components/schemas/AddSavingProductRequest"
                  }
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ProductResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/movements": {
      "post": {
        "tags": [
          "movement-controller"
        ],
        "operationId": "add",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "oneOf": [
                  {
                    "$ref": "#/components/schemas/DepositMovementRequest"
                  },
                  {
                    "$ref": "#/components/schemas/TransferMovementRequest"
                  },
                  {
                    "$ref": "#/components/schemas/WithdrawalMovementRequest"
                  }
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/MovementResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/login": {
      "post": {
        "tags": [
          "auth-controller"
        ],
        "operationId": "login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/customers": {
      "get": {
        "tags": [
          "customer-controller"
        ],
        "operationId": "findAll_1",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/CustomerResponse"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "customer-controller"
        ],
        "operationId": "create_1",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddCustomerRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/AddCustomerResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/products/{product}/status/{status}": {
      "patch": {
        "tags": [
          "product-controller"
        ],
        "operationId": "changeStatus",
        "parameters": [
          {
            "name": "product",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "status",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "enum": [
                "ACTIVE",
                "INACTIVE",
                "CANCELED"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/products/{product}": {
      "get": {
        "tags": [
          "product-controller"
        ],
        "operationId": "findByNumber",
        "parameters": [
          {
            "name": "product",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ProductResponse"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "product-controller"
        ],
        "operationId": "delete",
        "parameters": [
          {
            "name": "product",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "UpdateCustomerRequest": {
        "required": [
          "birthDate",
          "email",
          "lastName",
          "name"
        ],
        "type": "object",
        "properties": {
          "name": {
            "maxLength": 30,
            "minLength": 2,
            "type": "string"
          },
          "lastName": {
            "maxLength": 30,
            "minLength": 2,
            "type": "string"
          },
          "email": {
            "maxLength": 280,
            "minLength": 8,
            "type": "string"
          },
          "birthDate": {
            "type": "string",
            "format": "date"
          }
        }
      },
      "CustomerResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "documentType": {
            "type": "string",
            "enum": [
              "CC",
              "NIT",
              "FE",
              "PA"
            ]
          },
          "document": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "birthDate": {
            "type": "string",
            "format": "date"
          },
          "createdDate": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "AddCheckingProductRequest": {
        "required": [
          "balance",
          "customer",
          "gmf",
          "status"
        ],
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/AddProductRequest"
          },
          {
            "type": "object",
            "properties": {
              "customer": {
                "$ref": "#/components/schemas/CustomerRequest"
              },
              "gmf": {
                "type": "boolean"
              },
              "balance": {
                "type": "number"
              }
            }
          }
        ]
      },
      "AddProductRequest": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "enum": [
              "ACTIVE",
              "INACTIVE",
              "CANCELED"
            ]
          },
          "type": {
            "type": "string",
            "enum": [
              "CHECKING",
              "SAVINGS"
            ]
          }
        },
        "discriminator": {
          "propertyName": "type"
        }
      },
      "AddSavingProductRequest": {
        "required": [
          "balance",
          "customer",
          "gmf"
        ],
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/AddProductRequest"
          },
          {
            "type": "object",
            "properties": {
              "customer": {
                "$ref": "#/components/schemas/CustomerRequest"
              },
              "gmf": {
                "type": "boolean"
              },
              "balance": {
                "minimum": 1,
                "type": "number"
              }
            }
          }
        ]
      },
      "CustomerRequest": {
        "required": [
          "document",
          "documentType"
        ],
        "type": "object",
        "properties": {
          "documentType": {
            "type": "string",
            "enum": [
              "CC",
              "NIT",
              "FE",
              "PA"
            ]
          },
          "document": {
            "pattern": "^[A-Z0-9]{4,12}$",
            "type": "string"
          }
        }
      },
      "ProductResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "type": {
            "type": "string",
            "enum": [
              "CHECKING",
              "SAVINGS"
            ]
          },
          "status": {
            "type": "string",
            "enum": [
              "ACTIVE",
              "INACTIVE",
              "CANCELED"
            ]
          },
          "number": {
            "type": "integer"
          },
          "gmf": {
            "type": "boolean"
          },
          "balance": {
            "type": "number"
          },
          "createdDate": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "AddMovementRequest": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "DEPOSIT",
              "WITHDRAWAL",
              "TRANSFER"
            ]
          }
        },
        "discriminator": {
          "propertyName": "type"
        }
      },
      "DepositMovementRequest": {
        "required": [
          "amount",
          "number"
        ],
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/AddMovementRequest"
          },
          {
            "type": "object",
            "properties": {
              "number": {
                "type": "integer"
              },
              "amount": {
                "minimum": 1,
                "type": "number"
              }
            }
          }
        ]
      },
      "TransferMovementRequest": {
        "required": [
          "amount",
          "destinationNumber",
          "originNumber"
        ],
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/AddMovementRequest"
          },
          {
            "type": "object",
            "properties": {
              "originNumber": {
                "type": "integer"
              },
              "destinationNumber": {
                "type": "integer"
              },
              "amount": {
                "minimum": 1,
                "type": "number"
              }
            }
          }
        ]
      },
      "WithdrawalMovementRequest": {
        "required": [
          "amount",
          "number"
        ],
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/AddMovementRequest"
          },
          {
            "type": "object",
            "properties": {
              "number": {
                "type": "integer"
              },
              "amount": {
                "minimum": 1,
                "type": "number"
              }
            }
          }
        ]
      },
      "MovementResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "createdDate": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "LoginRequest": {
        "required": [
          "password",
          "username"
        ],
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "LoginResponse": {
        "type": "object",
        "properties": {
          "access_token": {
            "type": "string"
          }
        }
      },
      "AddCustomerRequest": {
        "required": [
          "birthDate",
          "document",
          "documentType",
          "email",
          "lastName",
          "name"
        ],
        "type": "object",
        "properties": {
          "documentType": {
            "type": "string",
            "enum": [
              "CC",
              "NIT",
              "FE",
              "PA"
            ]
          },
          "document": {
            "pattern": "^[A-Z0-9]{4,12}$",
            "type": "string"
          },
          "name": {
            "maxLength": 30,
            "minLength": 2,
            "type": "string"
          },
          "lastName": {
            "maxLength": 30,
            "minLength": 2,
            "type": "string"
          },
          "email": {
            "maxLength": 280,
            "minLength": 8,
            "type": "string"
          },
          "birthDate": {
            "type": "string",
            "format": "date"
          }
        }
      },
      "AddCustomerResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "createdDate": {
            "type": "string",
            "format": "date-time"
          }
        }
      }
    }
  }
}
