spring:
  application:
    name: ${MS_NAME:ms-manager-register}
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS:org.postgresql.Driver}
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/flypass}
    username: ${DATABASE_USERNAME:flypass}
    password: ${DATABASE_PASSWORD:flypass}
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: ${DATABASE_JPA_GENERATE_DDL:true}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH:/}

debug: ${DEBUG:false}

logging:
  level:
    org.springframework: info
    co.com.flypass: info

jwt:
  secret: "#r[gRsz24a?O{%?ndVJ>56#m^j;6:3%uqK77:xFsw6b7O)(fyiIbPkpM)p1LX$L"
  expiration: 60
